### ISSUE TITLE
Task: Create Universal Stablecoin Token List

### ISSUE THREAD

**Issue by kamescg** [district-labs/universal-sdk#26]
## Context

A priority for Universal is first-class stablecoin support.

## Scope
Create a new tokenlist that tracks canonical stablecoins and stablecoin derivatives on the major L2s.

The new token list should be added to the `universal-data` package.

Initial Stablecoins:
- USDC
- USDT
- USDS
- DAI
- PYUSD
- LUSD
- GUSD

Initial Chains:
- Ethereum (1)
- OP Mainnet (10)
- Base (8453)
- Arbitrum (42161)

**Comment by marthendalnunes** [comment]
- [ ] USDC
- [ ] USDT
- [ ] USDS
- [ ] DAI
- [ ] PYUSD
- [ ] LUSD
- [ ] GUSD
